shared:
    image: golang

jobs:
    main:
        steps:
            - echo: echo $SD_TOKEN
            - meta-set: meta set foo 1234567
            - meta-get: meta get foo
        requires: [~commit, ~sd@93:main]
        sourcePaths:
            - test/
